### PR TITLE
Feat/base

### PR DESCRIPTION
**Pull request by miladazhdehnia**
Added documents interfaces, http client, filters interfaces, and unbody base class based on Unbody GraphQL dashboard.
Please don't hesitate to suggest and asking for any improvements.
#2

### CODE REVIEW

**Comment by amirhouieh** [comment]
@miladazhdehnia Is there a demo for the POW functionality? If not, could you add one (not to be confused with unit test)? Thanks!

**Comment by miladazhdehnia** [comment]
There is no functionality implemented in this stage, it's just basic
interfaces.
First functionality will be shipped with the next pull request.

**Comment by miladazhdehnia** [comment]
> @miladazhdehnia Is there a demo for the POW functionality? If not, could you add one (not to be confused with unit test)? Thanks!

There is no functionality implemented in this stage, it's just basic interfaces.
First functionality will be shipped within the next pull request.

**Comment by amirhouieh** [comment]
> > @miladazhdehnia Is there a demo for the POW functionality? If not, could you add one (not to be confused with unit test)? Thanks!
> 
> There is no functionality implemented in this stage, it's just basic interfaces. First functionality will be shipped within the next pull request.

@jeangovil in that case LGTM.

**Review by jeangovil — APPROVED** [review]

**Review by amirhouieh — APPROVED** [review]

**Pull request merged**
